@startuml

class Card << (E,#7fff7f) >> {
    entity_id: String
    text: String
    date_creation: Date
    date_modification: Date
    tags[]: Tag
}

class Tag << (E,#7fff7f) >>{
    entity_id: String
    name: String
}

Card --> Tag
@enduml
